### ISSUE TITLE
Некорректный перевод (Incorrect translation)

### ISSUE THREAD

**Issue by konstantin-fedorov** [MicrosoftDocs/WSL.ru-RU#5]
Некорректный перевод
исходный текст: Обновление Windows 10 **пружины** 2018 (или более поздней версии)
должно быть: Обновление Windows 10 **весны** 2018 (или более поздней версии)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Ручная загрузка подсистемы Windows для Linux (WSL) дистрибутивов](https://docs.microsoft.com/ru-ru/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL.ru-ru/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @konstantin-fedorov
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Здравствуйте, @konstantin-fedorov.

Спасибо за Ваше предложение! 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
